Repository IDIOT-s/yes-slave, pull requests merged in 2023-12, with the labels that each got.

#1 feat: YSL-3 swagger 설정 추가
  build.gradle.kts
  src/main/java/org/idiot/yesslave/YesSlaveApplication.java
  src/main/java/org/idiot/yesslave/configuration/swagger/SwaggerConfig.java
Labels: 💻 setting

#2 chore: YSL-4 프로젝트 패키지 구성 설정
  src/main/java/org/idiot/yesslave/global/swagger/SwaggerConfig.java
  src/main/java/org/idiot/yesslave/sample/application/SampleService.java
  src/main/java/org/idiot/yesslave/sample/domain/Sample.java
  src/main/java/org/idiot/yesslave/sample/dto/SampleRequest.java
  src/main/java/org/idiot/yesslave/sample/dto/SampleResponse.java
  src/main/java/org/idiot/yesslave/sample/repository/SampleRepository.java
  src/main/java/org/idiot/yesslave/sample/ui/SampleController.java
Labels: 💻 setting

#6 feat: YSL-8 spring-boot-2.7.8-upgrade
  build.gradle.kts
Labels: 💻 setting

#7 chore: YSL-9 테스트 패키지 명 수정
  src/test/java/org/idiot/yesslave/YesSlaveApplicationTests.java
Labels: 🛠 refactor

#4 ci: YSL-2 CI 설정 추가
  .github/workflows/gradle.yml
Labels: 💻 setting

#5 feat: YSL-7 h2 database mode: mysql 설정
  src/main/resources/application.yml
Labels: 💻 setting

#8 feat: YSL-10 JPA Auditing 설정 추가
  src/main/java/org/idiot/yesslave/global/jpa/AuditInformation.java
Labels: ✨ feature
